name: Maven CI/CD

on:
  push:
    branches:
      - main
      - feature/login-pom
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chromium Browser
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Build, Test and Verify
        run: mvn -B verify -Dheadless=true

      - name: Upload Test Reports
        if: always() # Luôn chạy bước này, kể cả khi test thất bại
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/